### ISSUE TITLE
Accounts bug issue (replicated on multiple pc's)

### ISSUE THREAD

**Issue by jasonlt86** [hashitha/sigrisissues#11]
Clicking on the accounts button from anywhere results in a crash of RIS.exe 

Screenshots attached of event log. The 3 common error messages are:

Log Name:      Application
Source:        .NET Runtime
Date:          15/03/2016 5:07:24 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      BEEFY
Description:
Application: RIS.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at System.Reflection.RuntimeAssembly._nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.RuntimeAssembly.nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.Assembly.Load(System.Reflection.AssemblyName)
   at ᜁ.ᜳ.ᜀ(System.Reflection.AssemblyName)
   at ᜁ.ᜳ.ᜀ(System.String, System.String, System.String, System.Reflection.Assembly ByRef)
   at ᜁ.᜴..ctor()
   at TXTextControl.WPF.TextControl.ᜀ(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(System.Windows.DependencyObject, System.Windows.RoutedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(System.Object)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
   at System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
   at System.Windows.Media.MediaContext.Resize(System.Windows.Media.ICompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(MS.Internal.Interop.WindowMessage, IntPtr, IntPtr)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr, IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr, IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-03-15T09:07:24.979764200Z" />
    <EventRecordID>23000</EventRecordID>
    <Channel>Application</Channel>
    <Computer>BEEFY</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: RIS.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at System.Reflection.RuntimeAssembly._nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.RuntimeAssembly.nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.Assembly.Load(System.Reflection.AssemblyName)
   at ᜁ.ᜳ.ᜀ(System.Reflection.AssemblyName)
   at ᜁ.ᜳ.ᜀ(System.String, System.String, System.String, System.Reflection.Assembly ByRef)
   at ᜁ.᜴..ctor()
   at TXTextControl.WPF.TextControl.ᜀ(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(System.Windows.DependencyObject, System.Windows.RoutedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(System.Object)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
   at System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
   at System.Windows.Media.MediaContext.Resize(System.Windows.Media.ICompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(MS.Internal.Interop.WindowMessage, IntPtr, IntPtr)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr, IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr, IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        Application Error
Date:          15/03/2016 5:07:25 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      BEEFY
Description:
Faulting application name: RIS.exe, version: 1.0.0.0, time stamp: 0x56e77400
Faulting module name: KERNELBASE.dll, version: 10.0.10586.162, time stamp: 0x56cd55ab
Exception code: 0xe0434352
Fault offset: 0x000bdad8
Faulting process id: 0x53c
Faulting application start time: 0x01d17e98328fe222
Faulting application path: C:\Users\Jason\AppData\Local\Apps\2.0\LJLEHNJX.QHH\TYRQW88T.LR0\ris...tion_ae43a10ea7a15ddf_0002.0000_d6f4ee71a2a93684\RIS.exe
Faulting module path: C:\WINDOWS\SYSTEM32\KERNELBASE.dll
Report Id: a1931ee2-8d73-49af-b5a7-8afe85c484b9
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-03-15T09:07:25.056006400Z" />
    <EventRecordID>23001</EventRecordID>
    <Channel>Application</Channel>
    <Computer>BEEFY</Computer>
    <Security />
  </System>
  <EventData>
    <Data>RIS.exe</Data>
    <Data>1.0.0.0</Data>
    <Data>56e77400</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.10586.162</Data>
    <Data>56cd55ab</Data>
    <Data>e0434352</Data>
    <Data>000bdad8</Data>
    <Data>53c</Data>
    <Data>01d17e98328fe222</Data>
    <Data>C:\Users\Jason\AppData\Local\Apps\2.0\LJLEHNJX.QHH\TYRQW88T.LR0\ris...tion_ae43a10ea7a15ddf_0002.0000_d6f4ee71a2a93684\RIS.exe</Data>
    <Data>C:\WINDOWS\SYSTEM32\KERNELBASE.dll</Data>
    <Data>a1931ee2-8d73-49af-b5a7-8afe85c484b9</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

Log Name:      Application
Source:        Application Error
Date:          15/03/2016 5:09:48 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      BEEFY
Description:
Faulting application name: RIS.exe, version: 1.0.0.0, time stamp: 0x56e77400
Faulting module name: KERNELBASE.dll, version: 10.0.10586.162, time stamp: 0x56cd55ab
Exception code: 0xc000041d
Fault offset: 0x000bdad8
Faulting process id: 0x53c
Faulting application start time: 0x01d17e98328fe222
Faulting application path: C:\Users\Jason\AppData\Local\Apps\2.0\LJLEHNJX.QHH\TYRQW88T.LR0\ris...tion_ae43a10ea7a15ddf_0002.0000_d6f4ee71a2a93684\RIS.exe
Faulting module path: C:\WINDOWS\SYSTEM32\KERNELBASE.dll
Report Id: 2607a7c5-cac7-4b0a-b03b-a1f5d1058362
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-03-15T09:09:48.626555100Z" />
    <EventRecordID>23003</EventRecordID>
    <Channel>Application</Channel>
    <Computer>BEEFY</Computer>
    <Security />
  </System>
  <EventData>
    <Data>RIS.exe</Data>
    <Data>1.0.0.0</Data>
    <Data>56e77400</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.10586.162</Data>
    <Data>56cd55ab</Data>
    <Data>c000041d</Data>
    <Data>000bdad8</Data>
    <Data>53c</Data>
    <Data>01d17e98328fe222</Data>
    <Data>C:\Users\Jason\AppData\Local\Apps\2.0\LJLEHNJX.QHH\TYRQW88T.LR0\ris...tion_ae43a10ea7a15ddf_0002.0000_d6f4ee71a2a93684\RIS.exe</Data>
    <Data>C:\WINDOWS\SYSTEM32\KERNELBASE.dll</Data>
    <Data>2607a7c5-cac7-4b0a-b03b-a1f5d1058362</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by hashitha** [comment]
Fixed.
